---
abstract: "Mozilla's CA cert bundle in PEM format"
author:
  - 'Gisle Aas <gisle@activestate.com>'
build_requires:
  Test::More: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mozilla-CA
no_index:
  directory:
    - t
    - xt
resources:
  IRC: irc://irc.perl.org/#lwp
  bugtracker: https://github.com/libwww-perl/Mozilla-CA/issues
  license: https://www.mozilla.org/media/MPL/2.0/index.txt
  repository: https://github.com/libwww-perl/Mozilla-CA.git
version: '20230821'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
